export default {
  name: 'product',
  title: 'Product',
  type: 'document',
  fields: [
    { name: 'name', title: 'Product Name', type: 'string', validation: (R: any) => R.required() },
    { name: 'slug', title: 'Slug', type: 'slug', options: { source: 'name', maxLength: 96 }, validation: (R: any) => R.required() },
    { name: 'tagline', title: 'Tagline', type: 'string' },
    { name: 'shortDescription', title: 'Short Description', type: 'text', rows: 3 },
    { name: 'longDescription', title: 'Long Description', type: 'array', of: [{ type: 'block' }, { type: 'imageWithAlt' }] },
    {
      name: 'pricing', title: 'Pricing', type: 'object',
      fields: [
        { name: 'startingPrice', title: 'Starting Price (INR)', type: 'number' },
        { name: 'mrp', title: 'MRP (INR)', type: 'number' },
        { name: 'currency', title: 'Currency Symbol', type: 'string', initialValue: '₹' },
      ],
    },
    { name: 'sizes', title: 'Available Sizes', type: 'array', of: [{ type: 'sizeOption' }] },
    {
      name: 'specifications', title: 'Specifications', type: 'object',
      fields: [
        { name: 'thickness', title: 'Thickness', type: 'string' },
        { name: 'density', title: 'Density', type: 'string' },
        { name: 'purity', title: 'Purity', type: 'string' },
        { name: 'certification', title: 'Certification', type: 'string' },
        { name: 'feel', title: 'Feel / Firmness', type: 'string', options: { list: ['Soft', 'Medium-Soft', 'Medium', 'Medium-Firm', 'Firm', 'Extra Firm'] } },
        { name: 'material', title: 'Material', type: 'string' },
        { name: 'weight', title: 'Weight (kg)', type: 'string' },
      ],
    },
    { name: 'benefits', title: 'Key Benefits', type: 'array', of: [{ type: 'string' }] },
    {
      name: 'customOptions', title: 'Custom Builder Options', type: 'object',
      fields: [
        { name: 'available', title: 'Available for Custom Build', type: 'boolean' },
        { name: 'thicknessOptions', title: 'Thickness Options', type: 'array', of: [{ type: 'string' }] },
        { name: 'firmnessOptions', title: 'Firmness Options', type: 'array', of: [{ type: 'string' }] },
      ],
    },
    {
      name: 'shippingWarranty', title: 'Shipping and Warranty', type: 'object',
      fields: [
        { name: 'deliveryTime', title: 'Delivery Time', type: 'string' },
        { name: 'freeDelivery', title: 'Free Delivery', type: 'boolean' },
        { name: 'warrantyPeriod', title: 'Warranty Period', type: 'string' },
        { name: 'trialPeriod', title: 'Trial Period', type: 'string' },
        { name: 'returnPolicy', title: 'Return Policy Text', type: 'text', rows: 3 },
      ],
    },
    { name: 'images', title: 'Product Images', type: 'array', of: [{ type: 'imageWithAlt' }] },
    { name: 'video', title: 'Product Video URL', type: 'url' },
    { name: 'category', title: 'Category', type: 'reference', to: [{ type: 'brandCategory' }] },
    { name: 'tier', title: 'Product Tier', type: 'string', options: { list: [{ title: 'Comfort', value: 'comfort' }, { title: 'Premium', value: 'premium' }, { title: 'Luxury', value: 'luxury' }] } },
    { name: 'isBestseller', title: 'Bestseller', type: 'boolean' },
    { name: 'isNew', title: 'New Arrival', type: 'boolean' },
    { name: 'isFeatured', title: 'Featured on Homepage', type: 'boolean' },
    { name: 'inStock', title: 'In Stock', type: 'boolean', initialValue: true },
    { name: 'rating', title: 'Rating (out of 5)', type: 'number', validation: (R: any) => R.min(0).max(5) },
    { name: 'reviewCount', title: 'Review Count', type: 'number' },
    { name: 'relatedProducts', title: 'Related Products', type: 'array', of: [{ type: 'reference', to: [{ type: 'product' }] }], validation: (R: any) => R.max(4) },
    { name: 'seo', title: 'SEO Settings', type: 'pageSEO' },
  ],
  preview: { select: { title: 'name', subtitle: 'tagline', media: 'images[0]' } },
}
