export default {
  name: 'customBuilder',
  title: 'Mattress Builder',
  type: 'document',
  fields: [
    { name: 'header', title: 'Page header', type: 'object', fields: [
      { name: 'title', title: 'Title', type: 'string' },
      { name: 'subtitle', title: 'Subtitle', type: 'text', rows: 2 },
      { name: 'trustChips', title: 'Trust chips', type: 'array', of: [{ type: 'string' }] },
    ]},
    { name: 'sizes', title: 'Preset sizes', type: 'array', of: [{
      type: 'object', fields: [
        { name: 'name', title: 'Name', type: 'string' },
        { name: 'lengthInches', title: 'Length (in)', type: 'number' },
        { name: 'widthInches', title: 'Width (in)', type: 'number' },
        { name: 'basePrice', title: 'Base price (₹)', type: 'number', initialValue: 0 },
        { name: 'popular', title: 'Popular badge', type: 'boolean' },
      ],
    }]},
    { name: 'customSize', title: 'Custom size rules', type: 'object', fields: [
      { name: 'enabled', title: 'Allow custom size', type: 'boolean', initialValue: true },
      { name: 'unit', title: 'Default unit', type: 'string', options: { list: ['inches','cm'] } },
      { name: 'minLength', title: 'Min length', type: 'number' },
      { name: 'maxLength', title: 'Max length', type: 'number' },
      { name: 'minWidth', title: 'Min width', type: 'number' },
      { name: 'maxWidth', title: 'Max width', type: 'number' },
      { name: 'pricePerSqInch', title: 'Price per sq inch (₹)', type: 'number', initialValue: 0 },
      { name: 'cutCharge', title: 'Custom cut charge (₹)', type: 'number', initialValue: 0 },
      { name: 'helper', title: 'Helper text', type: 'string' },
    ]},
    { name: 'steps', title: 'Step copy', type: 'object', fields: [
      { name: 'sizeTitle', title: 'Step 1 title', type: 'string' },
      { name: 'sizeHelper', title: 'Step 1 helper', type: 'string' },
      { name: 'comfortTitle', title: 'Step 2 title', type: 'string' },
      { name: 'comfortHelper', title: 'Step 2 helper', type: 'string' },
      { name: 'supportTitle', title: 'Step 3 title', type: 'string' },
      { name: 'supportHelper', title: 'Step 3 helper', type: 'string' },
      { name: 'coverTitle', title: 'Step 4 title', type: 'string' },
      { name: 'coverHelper', title: 'Step 4 helper', type: 'string' },
    ]},
    { name: 'summaryPanel', title: 'Left summary panel copy', type: 'object', fields: [
      { name: 'heading', title: 'Heading', type: 'string', initialValue: 'Your Mattress' },
      { name: 'emptySlotText', title: 'Empty slot text', type: 'string', initialValue: 'Tap a step to choose' },
      { name: 'emiNote', title: 'EMI note template', type: 'string', description: 'Use {emi} token' },
      { name: 'perks', title: 'Perk microcopy', type: 'array', of: [{ type: 'string' }] },
    ]},
    { name: 'ctas', title: 'Call to action buttons', type: 'object', fields: [
      { name: 'primaryLabel', title: 'Primary button', type: 'string', initialValue: 'Add to cart' },
      { name: 'secondaryLabel', title: 'Secondary button', type: 'string', initialValue: 'Book a free consultation' },
      { name: 'disabledHint', title: 'Hint when incomplete', type: 'string' },
    ]},
    { name: 'defaults', title: 'Recommended default build', type: 'object', fields: [
      { name: 'sizeName', title: 'Default size name', type: 'string' },
      { name: 'comfortMaterialSlug', title: 'Default comfort material', type: 'string' },
      { name: 'comfortThickness', title: 'Default comfort thickness (in)', type: 'number' },
      { name: 'supportMaterialSlug', title: 'Default support material', type: 'string' },
      { name: 'supportThickness', title: 'Default support thickness (in)', type: 'number' },
      { name: 'coverFabricSlug', title: 'Default cover fabric', type: 'string' },
      { name: 'quiltingSlug', title: 'Default quilting (optional)', type: 'string' },
    ]},
    { name: 'seo', title: 'SEO', type: 'pageSEO' },
  ],
}
