export default {
  name: 'product',
  title: 'Product',
  type: 'document',
  fields: [
    { name: 'name', title: 'Product Name', type: 'string', validation: (R: any) => R.required() },
    { name: 'slug', title: 'Slug', type: 'slug', options: { source: 'name', maxLength: 96 }, validation: (R: any) => R.required() },
    { name: 'tagline', title: 'Tagline', type: 'string' },
    { name: 'subtitle', title: 'Subtitle', type: 'string' },
    { name: 'keyBenefit', title: 'Key Benefit', type: 'text', rows: 2 },
    { name: 'description', title: 'Description', type: 'text', rows: 5 },
    { name: 'badge', title: 'Badge', type: 'string' },
    { name: 'shortDescription', title: 'Short Description', type: 'text', rows: 3 },
    { name: 'longDescription', title: 'Long Description', type: 'array', of: [{ type: 'block' }, { type: 'imageWithAlt' }] },
    {
      name: 'comfortLevel', title: 'Comfort Level',
      type: 'string',
      options: { list: ['firm', 'medium-firm', 'medium', 'medium-soft', 'soft-medium', 'plush'] },
    },
    { name: 'comfortRating', title: 'Comfort Rating (1-5)', type: 'number', validation: (R: any) => R.min(1).max(5) },
    { name: 'totalThickness', title: 'Total Thickness (inches)', type: 'number' },
    {
      name: 'layers', title: 'Internal Architecture Layers', type: 'array', of: [{
        type: 'object',
        fields: [
          { name: 'thickness', title: 'Thickness (inches)', type: 'number' },
          { name: 'material', title: 'Material', type: 'string', options: { list: ['rebonded_foam', 'latex', 'hr_foam', 'hr_softy_foam', 'latex_rebonded', 'pu_rebonded'] } },
          { name: 'brand', title: 'Brand', type: 'string' },
          { name: 'certification', title: 'Certifications', type: 'array', of: [{ type: 'string' }] },
          { name: 'description', title: 'Description', type: 'text', rows: 2 },
        ],
      }],
    },
    { name: 'fabricGsm', title: 'Fabric GSM', type: 'number' },
    { name: 'fabricType', title: 'Fabric Type', type: 'string' },
    { name: 'certifications', title: 'Certifications', type: 'array', of: [{ type: 'string' }] },
    { name: 'accessories', title: 'Accessories Included', type: 'array', of: [{ type: 'string' }] },
    { name: 'warranty', title: 'Warranty (years)', type: 'number', initialValue: 10 },
    {
      name: 'pricingModel', title: 'Pricing Model',
      type: 'string',
      options: { list: [{ title: 'With / Without Accessories', value: 'with_without_accessories' }, { title: 'Fabric Options', value: 'fabric_options' }] },
    },
    {
      name: 'pricing', title: 'Pricing', type: 'object',
      fields: [
        { name: 'startingPrice', title: 'Starting Price (INR)', type: 'number' },
        { name: 'mrp', title: 'MRP (INR)', type: 'number' },
        { name: 'currency', title: 'Currency Symbol', type: 'string', initialValue: '₹' },
        {
          name: 'withAccessories', title: 'With Accessories', type: 'object',
          fields: [
            { name: 'king', title: 'King', type: 'number' }, { name: 'queen', title: 'Queen', type: 'number' },
            { name: 'double', title: 'Double', type: 'number' }, { name: 'single', title: 'Single', type: 'number' },
            { name: 'diwan', title: 'Diwan', type: 'number' }, { name: 'custom', title: 'Custom', type: 'number' },
          ],
        },
        {
          name: 'withoutAccessories', title: 'Without Accessories', type: 'object',
          fields: [
            { name: 'king', title: 'King', type: 'number' }, { name: 'queen', title: 'Queen', type: 'number' },
            { name: 'double', title: 'Double', type: 'number' }, { name: 'single', title: 'Single', type: 'number' },
            { name: 'diwan', title: 'Diwan', type: 'number' }, { name: 'custom', title: 'Custom', type: 'number' },
          ],
        },
        {
          name: 'fabric300Gsm', title: 'Fabric 300 GSM', type: 'object',
          fields: [
            { name: 'king', title: 'King', type: 'number' }, { name: 'queen', title: 'Queen', type: 'number' },
            { name: 'double', title: 'Double', type: 'number' }, { name: 'single', title: 'Single', type: 'number' },
            { name: 'diwan', title: 'Diwan', type: 'number' }, { name: 'custom', title: 'Custom', type: 'number' },
          ],
        },
        {
          name: 'fabric450Gsm', title: 'Fabric 450 GSM', type: 'object',
          fields: [
            { name: 'king', title: 'King', type: 'number' }, { name: 'queen', title: 'Queen', type: 'number' },
            { name: 'double', title: 'Double', type: 'number' }, { name: 'single', title: 'Single', type: 'number' },
            { name: 'diwan', title: 'Diwan', type: 'number' }, { name: 'custom', title: 'Custom', type: 'number' },
          ],
        },
      ],
    },
    { name: 'features', title: 'Features', type: 'array', of: [{ type: 'string' }] },
    { name: 'sizes', title: 'Available Sizes', type: 'array', of: [{ type: 'sizeOption' }] },
    {
      name: 'specifications', title: 'Specifications', type: 'object',
      fields: [
        { name: 'thickness', title: 'Thickness', type: 'string' },
        { name: 'density', title: 'Density', type: 'string' },
        { name: 'purity', title: 'Purity', type: 'string' },
        { name: 'certification', title: 'Certification', type: 'string' },
        { name: 'feel', title: 'Feel / Firmness', type: 'string', options: { list: ['Soft', 'Medium-Soft', 'Medium', 'Medium-Firm', 'Firm', 'Extra Firm'] } },
        { name: 'material', title: 'Material', type: 'string' },
        { name: 'weight', title: 'Weight (kg)', type: 'string' },
      ],
    },
    { name: 'benefits', title: 'Key Benefits', type: 'array', of: [{ type: 'string' }] },
    {
      name: 'customOptions', title: 'Custom Builder Options', type: 'object',
      fields: [
        { name: 'available', title: 'Available for Custom Build', type: 'boolean' },
        { name: 'thicknessOptions', title: 'Thickness Options', type: 'array', of: [{ type: 'string' }] },
        { name: 'firmnessOptions', title: 'Firmness Options', type: 'array', of: [{ type: 'string' }] },
      ],
    },
    {
      name: 'shippingWarranty', title: 'Shipping and Warranty', type: 'object',
      fields: [
        { name: 'deliveryTime', title: 'Delivery Time', type: 'string' },
        { name: 'freeDelivery', title: 'Free Delivery', type: 'boolean' },
        { name: 'warrantyPeriod', title: 'Warranty Period', type: 'string' },
        { name: 'trialPeriod', title: 'Trial Period', type: 'string' },
        { name: 'returnPolicy', title: 'Return Policy Text', type: 'text', rows: 3 },
      ],
    },
    { name: 'images', title: 'Product Images', type: 'array', of: [{ type: 'imageWithAlt' }] },
    { name: 'thumbnail', title: 'Thumbnail', type: 'imageWithAlt' },
    { name: 'video', title: 'Product Video URL', type: 'url' },
    { name: 'category', title: 'Category', type: 'reference', to: [{ type: 'brandCategory' }] },
    { name: 'tier', title: 'Product Tier', type: 'string', options: { list: [{ title: 'Comfort', value: 'comfort' }, { title: 'Premium', value: 'premium' }, { title: 'Luxury', value: 'luxury' }] } },
    { name: 'tags', title: 'Tags', type: 'array', of: [{ type: 'string' }] },
    { name: 'isBestseller', title: 'Bestseller', type: 'boolean' },
    { name: 'isNew', title: 'New Arrival', type: 'boolean' },
    { name: 'isFeatured', title: 'Featured on Homepage', type: 'boolean' },
    { name: 'inStock', title: 'In Stock', type: 'boolean', initialValue: true },
    { name: 'rating', title: 'Rating (out of 5)', type: 'number', validation: (R: any) => R.min(0).max(5) },
    { name: 'reviewCount', title: 'Review Count', type: 'number' },
    { name: 'sortOrder', title: 'Sort Order', type: 'number' },
    { name: 'relatedProducts', title: 'Related Products', type: 'array', of: [{ type: 'reference', to: [{ type: 'product' }] }], validation: (R: any) => R.max(6) },
    { name: 'crossSell', title: 'Cross Sell Products', type: 'array', of: [{ type: 'reference', to: [{ type: 'product' }] }] },
    { name: 'upsell', title: 'Upsell Products', type: 'array', of: [{ type: 'reference', to: [{ type: 'product' }] }] },
    { name: 'seo', title: 'SEO Settings', type: 'pageSEO' },
  ],
  preview: {
    select: { title: 'name', subtitle: 'tagline', media: 'images' },
    prepare({ title, subtitle, media }: any) {
      return { title, subtitle, media: media?.[0] }
    },
  },
}
