export default {
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  fields: [
    { name: 'branding', title: 'Branding', type: 'object', fields: [{ name: 'siteName', title: 'Site Name', type: 'string' }, { name: 'tagline', title: 'Tagline', type: 'string' }, { name: 'logo', title: 'Logo', type: 'imageWithAlt' }, { name: 'favicon', title: 'Favicon', type: 'image' }] },
    { name: 'navigation', title: 'Navigation', type: 'object', fields: [{ name: 'mainMenu', title: 'Main Menu', type: 'array', of: [{ type: 'navItem' }] }, { name: 'footerMenu', title: 'Footer Menu', type: 'array', of: [{ type: 'navItem' }] }, { name: 'ctaButton', title: 'Navbar CTA Button', type: 'ctaButton' }, { name: 'phoneNumber', title: 'Navbar Phone Number', type: 'string' }] },
    { name: 'footer', title: 'Footer', type: 'object', fields: [{ name: 'description', title: 'Footer Description', type: 'text', rows: 4 }, { name: 'socialLinks', title: 'Social Links', type: 'array', of: [{ type: 'socialLink' }] }, { name: 'certifications', title: 'Certification Badges', type: 'array', of: [{ type: 'object', fields: [{ name: 'name', title: 'Name', type: 'string' }, { name: 'image', title: 'Badge Image', type: 'imageWithAlt' }] }] }, { name: 'copyrightText', title: 'Copyright Text', type: 'string' }] },
    { name: 'contactInfo', title: 'Global Contact Info', type: 'object', fields: [{ name: 'mainPhone', title: 'Main Phone', type: 'string' }, { name: 'secondaryPhone', title: 'Secondary Phone', type: 'string' }, { name: 'whatsappNumber', title: 'WhatsApp Number', type: 'string' }, { name: 'whatsappDefaultMessage', title: 'Default WhatsApp Message', type: 'text', rows: 2 }, { name: 'email', title: 'Email', type: 'string' }, { name: 'factoryAddress', title: 'Factory Address', type: 'text', rows: 3 }] },
    { name: 'announcement', title: 'Announcement Banner', type: 'object', fields: [{ name: 'showBanner', title: 'Show Banner', type: 'boolean' }, { name: 'bannerText', title: 'Banner Text', type: 'string' }, { name: 'bannerLink', title: 'Banner Link', type: 'string' }, { name: 'bannerColor', title: 'Banner Color', type: 'string', options: { list: ['green', 'blue', 'red', 'yellow'] } }] },
    {
      name: 'staticImages', title: 'Static Brand Images', type: 'object',
      fields: [
        { name: 'gotsCotton', title: 'GOTS Organic Cotton', type: 'imageWithAlt' },
        { name: 'quiltedCotton', title: 'Quilted Organic Cotton', type: 'imageWithAlt' },
        { name: 'naturalLatex', title: '100% Natural Latex', type: 'imageWithAlt' },
        { name: 'comfortMeter', title: 'Comfort Meter Chart', type: 'imageWithAlt' },
        { name: 'sizeChart', title: 'Size Chart', type: 'imageWithAlt' },
        { name: 'heroBedroom', title: 'Hero Bedroom Background', type: 'imageWithAlt' },
      ],
    },
    { name: 'seo', title: 'Default SEO', type: 'pageSEO' },
    { name: 'analytics', title: 'Analytics and Tracking', type: 'object', fields: [{ name: 'gaTrackingId', title: 'Google Analytics ID', type: 'string' }, { name: 'metaPixelId', title: 'Meta Pixel ID', type: 'string' }, { name: 'gtmId', title: 'Google Tag Manager ID', type: 'string' }] },
    {
      name: 'leadPopup', title: 'Lead Capture Popup',
      description: 'Configure the lead capture popup that appears to collect visitor information.',
      type: 'object',
      fields: [
        { name: 'enabled', title: 'Enable Popup', type: 'boolean', initialValue: true },
        { name: 'heading', title: 'Heading', type: 'string', initialValue: 'Get Exclusive Offers' },
        { name: 'description', title: 'Description', type: 'text', rows: 2, initialValue: 'Get personalized mattress recommendations and exclusive pricing directly from our sleep experts.' },
        { name: 'badgeText', title: 'Badge Text', type: 'string', initialValue: '🎁 Limited-Time Offer' },
        { name: 'ctaLabel', title: 'CTA Button Text', type: 'string', initialValue: 'Get My Offer' },
        { name: 'successHeading', title: 'Success Heading', type: 'string', initialValue: '✅ Thank You!' },
        { name: 'successDescription', title: 'Success Description', type: 'text', rows: 2, initialValue: 'Our sleep expert will contact you shortly.' },
        { name: 'trustTexts', title: 'Trust Badges', type: 'array', of: [{ type: 'string' }],
          description: 'List of trust messages shown below the form (e.g. "No Spam", "Expert Assistance").',
          initialValue: ['No Spam', 'Expert Assistance', 'Exclusive Deals']
        },
        { name: 'disclaimer', title: 'Disclaimer Text', type: 'string', initialValue: 'By submitting this form you agree to be contacted via call, WhatsApp or email.' },
        { name: 'dontShowAgainText', title: '"Don\'t Show Again" Text', type: 'string', initialValue: 'Don\'t show this again' },
        { name: 'showLogo', title: 'Show Logo', type: 'boolean', initialValue: true },
        { name: 'initialDelay', title: 'Initial Delay (seconds)', type: 'number', initialValue: 2, description: 'How long after page load before the popup first appears.' },
        { name: 'cooldownSeconds', title: 'Cooldown (seconds)', type: 'number', initialValue: 12, description: 'Minimum time between popup closes and re-appearance.' },
        { name: 'scrollPercent', title: 'Scroll Trigger (%)', type: 'number', initialValue: 40, description: 'Show popup when user scrolls past this percentage of the page.' },
        { name: 'submittingText', title: 'Submitting Button Text', type: 'string', initialValue: 'Submitting...' },
      ],
    },
    {
      name: 'certificates', title: 'Certificate PDF Links', type: 'array',
      description: 'Certification documents displayed on the website. Add ISO, OEKO-TEX, and GOLS certificates here.',
      of: [{
        type: 'object',
        fields: [
          { name: 'id', title: 'ID', type: 'string', description: 'Unique identifier (e.g. iso, oeko, gols)', validation: Rule => Rule.required() },
          { name: 'title', title: 'Title', type: 'string', validation: Rule => Rule.required() },
          { name: 'subtitle', title: 'Subtitle', type: 'string' },
          { name: 'description', title: 'Description', type: 'text', rows: 3 },
          { name: 'pdfUrl', title: 'PDF View URL', type: 'string', description: 'Google Drive view link (e.g. https://drive.google.com/file/d/.../view)' },
          { name: 'pdfEmbedUrl', title: 'PDF Embed URL', type: 'string', description: 'Google Drive embed link for iframe (e.g. https://drive.google.com/file/d/.../preview)' },
          { name: 'validity', title: 'Validity Text', type: 'string', description: 'e.g. "Valid — Audited Annually"' },
        ],
        preview: {
          select: { title: 'title', subtitle: 'id' },
        },
      }],
    },
  ],
}
